### ISSUE TITLE
Prettier 세팅

### ISSUE THREAD

**Issue by unbroken2650** [TEAM-MAT/gomin-sageori#20]
https://techwell.wooritech.com/docs/tools/prettier/prettier-eslint-airbnb/

**Comment by makemyway-kr** [comment]
react code에만 적용하는거 아니면 전체 다?

**Comment by unbroken2650** [comment]
자바는 나름대로 적용해야겠지?

**Comment by makemyway-kr** [comment]
> 자바는 나름대로 적용해야겠지?

ㅇㅋㅇ
