### ISSUE TITLE
front 수정사항

### ISSUE THREAD

**Issue by makemyway-kr** [TEAM-MAT/gomin-sageori#23]
<img width="1518" alt="image" src="https://user-images.githubusercontent.com/58161987/166915018-6d6d0962-df19-4448-a0ae-55417430117f.png">

1. 확인(submit)버튼..? 만들어야 하는지 아니면 모두 다 입력하면 자동으로 호출하게 해둔건지
2. setUpProxy작성하기(해결완료)

**Comment by unbroken2650** [comment]
1. 확인 버튼 만들어둠(완료)

**Comment by makemyway-kr** [comment]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/58161987/166921146-5580c1b7-7121-441c-9478-7751a26cf4b3.png">
Bunch of errors happening

API호출은 잘 됨.

**Comment by makemyway-kr** [comment]
API호출 잘 되는 것 확인.
