### ISSUE TITLE
Prefer button Disable 개선

### ISSUE THREAD

**Issue by unbroken2650** [TEAM-MAT/gomin-sageori#39]
https://github.com/TEAM-MAT/gomin-sageori/blob/3697ad1c1d8168db44b0b93e7cff993de45d56bb/gomin-sageori_front/src/pages/Main.js#L112-L125

3개만 선택할 수 있는거 만들다가 생각해봤는데,
disable 하는 것보다 없음일 때 클릭이 isSelected 로 안 넘어가게 하면 더 간단하게 될 거 같은데 어떻게 생각하시나요?
@intersoom @makemyway-kr

**Comment by makemyway-kr** [comment]
근데 UI적으로 선택이 안된다는걸 보여줄 수 있어야 하지 않을까?

**Comment by unbroken2650** [comment]
@makemyway-kr 변수를 줄이는 거지 기능을 없애는 건 아닌데?
'없음'이 클릭 되어 있을 때 클릭하면 안 되는 거 보여주면 되지

**Comment by intersoom** [comment]
옹 그런 방법이 있었네요 그렇게 하면 코드는 더 간단해질듯?

**Comment by intersoom** [comment]
UI적으로 선택이 어렵다는걸 보여주는 방법은 클릭해보는 것 뿐이라서 투명도 조절 같은 것도 할 수 있으면 좋긴 할듯?

**Comment by unbroken2650** [comment]
@intersoom 근데 또 없음은 클릭이 돼야 하니까 지금처럼 해도 괜찮을 거 같기도 하고..! 일단 그대로 해볼게 3개만 선택하는 거부터

**Comment by makemyway-kr** [comment]
해보고 한번 보자 어떻게 되는지

**Comment by unbroken2650** [comment]
현상 유지로 일단 작업중
